/** 環境變數 Keys, 包含所有應用程式所需的環境變數 */
export type EnvironmentKey =
  | 'TELEGRAM_BOT_TOKEN'
  | 'TELEGRAM_CONNECT_MODE'
  | 'DB_TYPE'
  | 'DB_HOST'
  | 'DB_PORT'
  | 'DB_USER'
  | 'DB_PASSWORD'
  | 'DB_NAME'
  | 'DB_SYNCHRONIZE'
  | 'DB_LOGGING'
  | 'REDIS_HOST'
  | 'REDIS_PORT'
  | 'REDIS_PASSWORD'
  | 'REDIS_DB'
  | 'WHISPER_LOCAL_API_URL'
  | 'AZURE_SPEECH_KEY'
  | 'AZURE_SPEECH_REGION'
  | 'AZURE_SPEECH_ENDPOINT'
  | 'OLLAMA_API_URL'
  | 'OLLAMA_MODEL'
  | 'NODE_ENV'
