export enum EnvironmentKey {
  // Telegram
  TELEGRAM_BOT_TOKEN = 'TELEGRAM_BOT_TOKEN',
  TELEGRAM_CONNECT_MODE = 'TELEGRAM_CONNECT_MODE',
  // Database
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
  DB_LOGGING = 'DB_LOGGING',
  // Redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_DB = 'REDIS_DB',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  // Whisper
  WHISPER_LOCAL_API_URL = 'WHISPER_LOCAL_API_URL',
  // Azure Speech (Pronunciation)
  AZURE_SPEECH_KEY = 'AZURE_SPEECH_KEY',
  AZURE_SPEECH_REGION = 'AZURE_SPEECH_REGION',
  AZURE_SPEECH_ENDPOINT = 'AZURE_SPEECH_ENDPOINT',
  // Ollama
  OLLAMA_API_URL = 'OLLAMA_API_URL',
  OLLAMA_MODEL = 'OLLAMA_MODEL',
  // Node
  NODE_ENV = 'NODE_ENV',
}
export type TelegramConnectMode = 'long-polling' | 'webhook'
